### ISSUE TITLE
Analyze Video Error

### ISSUE THREAD

**Issue by JakeMalis** [sararob/video-intelligence-demo#18]
<img width="1280" alt="screen shot 2017-04-19 at 10 43 30 am" src="https://cloud.githubusercontent.com/assets/18268912/25188046/bf7175c2-24f2-11e7-9aee-15f159ecb181.png">

When I upload a video to the footage bucket, I get this error, and it doesn't print the JSON output.

**Comment by koloszko** [comment]
I had the same problem. It seems that uploaded video files have to be shared publicly to make this demo work. I have changed permission to my video bucket as you can see below
![image](https://cloud.githubusercontent.com/assets/2341208/25330473/13b53e70-28e0-11e7-8990-a0c19a1d2ed9.png)
and now JSON output is printed as it should be.

**Comment by JakeBMalis** [comment]
That still doesn't work.

**Comment by koloszko** [comment]
It seems that you also need change object default permissions the same way. So choose this
![image](https://cloud.githubusercontent.com/assets/2341208/25429330/e7fc9298-2a78-11e7-9d84-cfbce926c4ba.png)
for your video bucket and add item:
_User - allUsers - Reader_

**Comment by sararob** [comment]
@JakeBMalis yes, right now for this to work you need to set object default permissions to public. I'm working on a better solution for this, will update the repo / readme when I have a fix.

**Comment by wsycy2000** [comment]
if anyone teach me about how to use the project after download the zip.
