### ISSUE TITLE
The chrome does not take me to the video playback page when clicking the thumbnail

### ISSUE THREAD

**Issue by domaemon** [sararob/video-intelligence-demo#21]
Hoping that I am not the only one who can reproduce this issue. Thanks.

=== Steps to produce ===
1. Follow the README instruction and start the frontend locally.
2. Open 'http://localhost:8080/' in chrome (new incognito window)
3. Click on the video thumbnail

=== Expected result ===
The chrome takes me to the video playback page.

=== Actual result ===
The url on the address-bar changes to 'http://localhost:8080/video/google-home-superbowl-mp4', but the the chrome does not take me to the actual video playback page.

=== Note ===
* If I enter 'http://localhost:8080/video/google-home-superbowl-mp4' in the address bar and hit Return, then the chrome takes me to the video playback page.
* Tried hard refreshing the browser, the result did not change.
* Looked at the developer console, but could not find any error message.
* The similar behaviour can be observed for other links, such as search (type keyword and hit Return) and 'Video Intelligence' on the top left.

**Comment by sararob** [comment]
What version of Chrome are you using? I'm not able to repro on Chrome or Safari. I'm on a Mac with Chrome Version 58.0.3029.110.

I have had someone else report this issue, trying to get to the bottom of it.

**Comment by domaemon** [comment]
Thanks so much for looking into it. Here are the environments I've tested on. I could reproduce the issue on all.

1. MacOS Sierra 10.12.4 + Chrome Version 58.0.3029.110
2. MacOS Sierra 10.12.4 + Chrome Version 60.0.3109.0 (Canary)
3. MacOS Sierra 10.12.4 + Safari Version 10.1 (12603.1.30.0.34)
4. Nexus 7 Android 6.0.1 + Chrome Version (Default)

**Comment by domaemon** [comment]
The following change solved the issue in my environment.

===
--- a/frontend/resources/js/index.js
+++ b/frontend/resources/js/index.js
@@ -62,7 +62,7 @@ class App {
   }

   initRouter() {
-    this.router = new navigo(null, false);
+    this.router = new navigo(null, true);
     this.router.updatePageLinks();

**Comment by siddhant-curious** [comment]
@domaemon doing so makes http://localhost:8080/profile redirect to http://localhost:8080 making /profile unreachable.

**Comment by jmsfcb** [comment]
@siddhant-curious You can still get to the profile from http://localhost:8080/#/profile.

That router is doing weird things.

**Comment by sararob** [comment]
This should be fixed in the latest commit. It was related to a new version of `navigo` which is used for the router, so you'll want to make sure you've got the latest installed.

**Comment by domaemon** [comment]
Tested with the latest update. The issue is fixed, closing. Thanks.
