### ISSUE TITLE
generatePreview ENOENT problem

### ISSUE THREAD

**Issue by quochuypho** [sararob/video-intelligence-demo#25]
Anyone had this issue?

![generatepreview](https://user-images.githubusercontent.com/30616683/34463748-58a6d8c6-ee66-11e7-96ff-bd6c66daa6d5.jpg)

**Comment by quochuypho** [comment]
/user_code/ffmpeg/ffprobe ENOENT at exports._errnoException

solved by downloading the ffmpeg build and set the registry to the bin folder
setx /M PATH "folder_to_bin;%PATH%"

**Comment by af001** [comment]
@quochuypho where did you run setx /M PATH "folder_to_bin:%PATH%"??
